from opentrons import protocol_api

# Simulate with:
#   opentrons_simulate -L CUSTOM_LABWARE_DIR ccIHC_cycle1_Pan-CK.py
#
# Generated by make_ccihc_protocols.py - edit freely, or edit the generator and
# regenerate. Cycle 1 of 2.
#
# Slides are loaded and unloaded by the robot arm. This protocol ends with the
# sections sitting under MQ water, ready to be lifted onto the microscope.
#
# Done manually, off-deck, before this run:
#   - (cycle 1 only) deparaffinisation, rehydration, HIER in Tris-EDTA pH 9
#   - StreptaClick HRP labelling of the biotinylated primary, Biotin Block
#     Buffer addition, dilution in 0.5% BSA/PBS -> load into A3
#   - AEC substrate mixed from ImmPACT reagents 1-3 and filtered
#   - HRP Block Buffer activated with H2O2 + Block Activator

# ==============================================================================
# CYCLE-SPECIFIC CONFIGURATION
# ==============================================================================
CYCLE_INDEX = 1
CYCLE_TOTAL = 2
IS_LAST_CYCLE = False

# Cycles 2..N start by stripping the previous cycle's AEC and haematoxylin and
# quenching the previous HRP. Cycle 1 skips straight to staining.
RUN_DESTAIN_FIRST = False

ANTIBODY = {
    'name':        'Pan-CK',
    'description': 'Pan-CK (ab80826-biotin) + StreptaClick HRP, 1:100',
    'well':        'A3',        # Eppendorf rack, slot 2
    'color':       '#1475BF',
    'slides':      None,        # None = every non-control slide
}

metadata = {
    'protocolName': 'ccIHC cycle 1/2 - Pan-CK',
    'description': ('Cyclic chromogenic IHC on FFPE sections, StreptaClick HRP + AEC. '
                    'Cycle 1: Pan-CK (ab80826-biotin) + StreptaClick HRP, 1:100'),
    'author': 'Franziska Niemeyer',
}
requirements = {"robotType": "OT-2", 'apiLevel': '2.18'}

# ==============================================================================
# SHARED CONFIGURATION - keep identical across all cycle files
# ==============================================================================

# --- Slides -------------------------------------------------------------------
BOX_SIZES = {'box1': 6, 'box2': 0}

# 0-indexed across box1 then box2. These get 0.5% BSA/PBS instead of antibody.
NEG_CONTROL_SLIDES = [0]

# --- Volumes ------------------------------------------------------------------
REAGENT_VOLUME = 120          # ul per section per reagent application
WASH_VOLUME = 120                # ul per wash exchange
ANTIBODY_INCUBATION_MIN = 60

# --- Protocol switches --------------------------------------------------------
HRP_BLOCK_EVERY_CYCLE = True  # False = only in cycle 1; the inter-cycle
                                             # Quench Buffer then carries the load
START_PAUSE = False                # True = confirm deck before starting

# --- Liquid handling ----------------------------------------------------------
# Nothing is aspirated out during this protocol: each addition displaces the
# previous liquid over the chamber lip. Run drain_chambers.py whenever the
# chambers need to be emptied properly.
DISPENSE_Z = -2.0          # mm below well top when dispensing, so the tip never
                           # enters the liquid and cannot carry over between slides

# Anti-evaporation top-ups during the long antibody incubation. Set False if the
# staining box has a humidified lid.
TOPUP_LONG_INCUBATIONS = True
TOPUP_INTERVAL_MIN = 20
TOPUP_VOLUME = 30

# --- Reagent positions --------------------------------------------------------
# Falcon 10-tube rack, slot 3. Well naming of
# opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical:
#   15 ml -> A1, B1, C1, A2, B2, C2      50 ml -> A3, B3, A4, B4   (no A5!)
FALCON_WELLS = {
    'hematoxylin':  'A1',      # 15 ml, filtered
    'aec':          'A2',      # 15 ml, store up to 14 days at +4
    'hrp-block':    'B1',      # 15 ml, activated HRP Block Buffer
    'quench':       'B2',      # 15 ml, Kromnigon HRP Quench Buffer
    'bsa':          'C2',      # 15 ml, 0.5% BSA in PBS
    'pbs':          'A3',      # 50 ml
    'mq':           'B3',      # 50 ml
    'eth70':        'A4',      # 50 ml
    'eth96':        'B4',      # 50 ml
}

# Fill volumes in ul at the START OF THIS CYCLE. Volume tracking does not carry
# over between protocol runs, so top the tubes up between cycles - or set these
# to what is actually left and let the refill pause catch a shortfall.
FILL_VOLUMES = {
    'bsa':          6000,
    'hrp-block':    5000,
    'aec':          5000,
    'hematoxylin':  5000,
    'quench':       5000,
    'eth70':        45000,
    'eth96':        45000,
    'pbs':          45000,
    'mq':           45000,
}
DEAD_VOLUME = {'1.5ml': 80, '15ml': 800, '50ml': 3000}

# --- Deck ---------------------------------------------------------------------
SLOT_BOX1, SLOT_BOX2 = 1, 4
SLOT_EPPENDORF, SLOT_FALCON = 2, 3
SLOTS_TIPRACKS = [8, 9]

# ==============================================================================
# END OF CONFIGURATION
# ==============================================================================

# Conical geometry for liquid-level tracking:
#   (cross-section mm2, cone height mm, cone volume ul, minimum z mm)
TUBE_GEOMETRY = {
    '1.5ml': (59.4,  17.8,  352.0, 2.0),
    '15ml':  (174.4, 22.0, 1279.0, 3.0),
    '50ml':  (607.3, 15.0, 3037.0, 3.0),
}
SUBMERGE_MM = 5.0


class Reagent:
    """A source tube with volume tracking and an automatic refill pause."""

    def __init__(self, key, well, volume, tube, description='', color='#808080'):
        self.key, self.well, self.tube = key, well, tube
        self.fill = self.volume = volume
        self.used = 0.0
        self.description, self.color = description, color

    def source(self, protocol, needed):
        """Reserve `needed` ul, pausing for a refill if the tube would run dry."""
        if self.volume - needed < DEAD_VOLUME[self.tube]:
            protocol.pause(
                f"Refill {self.key} at {self.well} to {self.fill / 1000:.0f} ml "
                f"(next step needs {needed / 1000:.1f} ml), then resume."
            )
            self.volume = self.fill
        self.volume -= needed
        self.used += needed
        return self.well.bottom(self._z())

    def _z(self):
        area, cone_h, cone_v, min_z = TUBE_GEOMETRY[self.tube]
        v = max(self.volume, 0.0)
        surface = (cone_h * (v / cone_v) ** (1 / 3) if v <= cone_v
                   else cone_h + (v - cone_v) / area)
        return max(min_z, surface - SUBMERGE_MM)


def run(protocol: protocol_api.ProtocolContext):

    # ==========================================================================
    # Deck and slides
    # ==========================================================================
    n1, n2 = BOX_SIZES['box1'], BOX_SIZES['box2']
    num_slides = n1 + n2

    tips = [protocol.load_labware('opentrons_96_tiprack_1000ul', s) for s in SLOTS_TIPRACKS]
    box1 = protocol.load_labware('stainchambertest_8well', SLOT_BOX1, '8 well stain chamber')
    all_wells = box1.wells()[:n1]
    if n2 > 0:
        box2 = protocol.load_labware('stainchambertest_8well', SLOT_BOX2, '8 well stain chamber')
        all_wells += box2.wells()[:n2]

    eppie = protocol.load_labware('opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap',
                                  SLOT_EPPENDORF)
    falcon = protocol.load_labware('opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical',
                                   SLOT_FALCON)
    pipette = protocol.load_instrument('p1000_single_gen2', 'right', tip_racks=tips)

    dest_all = all_wells
    neg_wells = [all_wells[i] for i in NEG_CONTROL_SLIDES]
    stained = [w for i, w in enumerate(all_wells) if i not in NEG_CONTROL_SLIDES]
    ab_wells = stained if ANTIBODY['slides'] is None else [all_wells[i] for i in ANTIBODY['slides']]

    # ==========================================================================
    # Reagents
    # ==========================================================================
    reagents = {}

    def register(key, well, tube, volume, description, color):
        r = Reagent(key, well, volume, tube, description, color)
        well.load_liquid(liquid=protocol.define_liquid(name=key, description=description,
                                                       display_color=color),
                         volume=volume)
        reagents[key] = r
        return r

    for key, tube, desc, color in [
        ('bsa',         '15ml', '0.5% BSA in PBS - block, diluent, negative control', '#9DBC98'),
        ('hrp-block',   '15ml', 'Activated HRP Block Buffer (Kromnigon + H2O2)',      '#2CB4CF'),
        ('aec',         '15ml', 'ImmPACT AEC substrate, premixed and filtered',       '#B03030'),
        ('hematoxylin', '15ml', 'Filtered haematoxylin, aqueous-compatible',          '#3B2E8F'),
        ('quench',      '15ml', 'Kromnigon HRP Quench Buffer',                        '#720455'),
        ('pbs',         '50ml', '1x PBS',                                             '#7FBF7F'),
        ('mq',          '50ml', 'MQ water',                                           '#DDDDDD'),
        ('eth70',       '50ml', '70% ethanol - AEC removal',                          '#BFD7EA'),
        ('eth96',       '50ml', '96% ethanol - AEC removal',                          '#8FB8D8'),
    ]:
        register(key, falcon[FALCON_WELLS[key]], tube, FILL_VOLUMES[key], desc, color)
    bsa = reagents['bsa']

    n_top = (max(0, int(ANTIBODY_INCUBATION_MIN // TOPUP_INTERVAL_MIN) - 1)
             if TOPUP_LONG_INCUBATIONS else 0)
    ab_volume = (len(ab_wells) * (REAGENT_VOLUME + n_top * TOPUP_VOLUME)
                 + DEAD_VOLUME['1.5ml'] + 100)
    if ab_volume > 1500:
        protocol.comment(f"WARNING: {ANTIBODY['name']} needs {ab_volume} ul, more than a "
                         "1.5 ml tube holds. Use fewer slides or a 15 ml tube.")
    antibody = register(ANTIBODY['name'], eppie[ANTIBODY['well']], '1.5ml', ab_volume,
                        ANTIBODY['description'], ANTIBODY['color'])

    # ==========================================================================
    # Liquid handling
    # ==========================================================================
    def dispense_to(reagent, wells, volume, keep_tip=False, has_tip=False):
        """Distribute `volume` into every well from above the liquid line."""
        targets = [w.top(DISPENSE_Z) for w in wells]
        src = reagent.source(protocol, volume * len(wells))
        if not has_tip:
            pipette.pick_up_tip()
        pipette.distribute(volume, src, targets,
                           new_tip="never", blow_out=True,
                           blowout_location="source well",
                           disposal_vol=0, air_gap=10)
        if not keep_tip:
            pipette.drop_tip()

    def incubate(minutes, topup_groups=None):
        """Delay, periodically topping up open wells to limit evaporation."""
        if not (TOPUP_LONG_INCUBATIONS and topup_groups) or minutes <= TOPUP_INTERVAL_MIN:
            if minutes:
                protocol.delay(minutes=minutes)
            return
        elapsed = 0.0
        while minutes - elapsed > TOPUP_INTERVAL_MIN:
            protocol.delay(minutes=TOPUP_INTERVAL_MIN)
            elapsed += TOPUP_INTERVAL_MIN
            protocol.comment(f"Evaporation top-up at {elapsed:.0f} min")
            for reagent, wells in topup_groups:
                if wells:
                    dispense_to(reagent, wells, TOPUP_VOLUME)
        protocol.delay(minutes=minutes - elapsed)

    def apply(reagent, wells, volume=REAGENT_VOLUME, minutes=0, seconds=0,
              topup=False, note=None):
        """One reagent application followed by its incubation."""
        if isinstance(wells, protocol_api.labware.Well):
            wells = [wells]
        if note:
            protocol.comment(note)
        dispense_to(reagent, wells, volume)
        incubate(minutes + seconds / 60.0,
                 topup_groups=[(reagent, wells)] if topup else None)

    def wash(reagent, wells, n=1, volume=WASH_VOLUME, minutes=0, seconds=0, note=None):
        """n displacement exchanges of the same buffer, on a single tip."""
        if note:
            protocol.comment(note)
        pipette.pick_up_tip()
        for i in range(n):
            dispense_to(reagent, wells, volume, keep_tip=True, has_tip=True)
            if minutes or seconds:
                protocol.delay(minutes=minutes, seconds=seconds)
        pipette.drop_tip()

    # ==========================================================================
    # PROTOCOL
    # ==========================================================================
    protocol.comment(f"CYCLE {CYCLE_INDEX}/{CYCLE_TOTAL} - {ANTIBODY['name']} - "
                     f"{num_slides} slides, {len(NEG_CONTROL_SLIDES)} negative control(s)")
    if START_PAUSE:
        protocol.pause(f"Cycle {CYCLE_INDEX}: confirm slides are loaded and "
                       f"{ANTIBODY['name']} conjugate is in {ANTIBODY['well']}, then resume.")

    # --- 0. Inter-cycle treatment (cycles 2..N) -------------------------------
    if RUN_DESTAIN_FIRST:
        protocol.comment("Inter-cycle: AEC removal, haematoxylin clearing, HRP quench")
        apply(reagents['eth70'], dest_all, minutes=2, note="70% EtOH, 2 min")
        apply(reagents['eth96'], dest_all, minutes=2, note="96% EtOH, 2 min")
        apply(reagents['eth70'], dest_all, minutes=2, note="70% EtOH, 2 min")
        wash(reagents['mq'], dest_all, n=1, note="MQ")
        apply(reagents['quench'], dest_all, minutes=10, note="HRP Quench Buffer, 10 min")
        wash(reagents['pbs'], dest_all, n=4, seconds=15, note="Wash 4x PBS, 15 s each")

    # --- 1. Endogenous peroxidase block ---------------------------------------
    if HRP_BLOCK_EVERY_CYCLE or CYCLE_INDEX == 1:
        apply(reagents['hrp-block'], dest_all, minutes=14,
              note="Activated HRP Block Buffer, 14 min")
        wash(reagents['mq'], dest_all, n=3, note="Wash 3x MQ")
        wash(reagents['pbs'], dest_all, n=1, seconds=30, note="PBS, 30 s")

    # --- 2. Block non-specific protein interactions ---------------------------
    apply(bsa, dest_all, minutes=10, note="0.5% BSA/PBS, 10 min")

    # --- 3. HRP-labelled primary ----------------------------------------------
    # No wash after the BSA block: the manual protocol flicks the BSA off and
    # applies the antibody straight on top.
    protocol.comment(f"HRP-labelled {ANTIBODY['name']}, {ANTIBODY_INCUBATION_MIN} min")
    dispense_to(antibody, ab_wells, REAGENT_VOLUME)
    if neg_wells:
        protocol.comment("Negative controls: 0.5% BSA/PBS instead of antibody")
        dispense_to(bsa, neg_wells, REAGENT_VOLUME)
    incubate(ANTIBODY_INCUBATION_MIN,
             topup_groups=[(antibody, ab_wells), (bsa, neg_wells)])

    wash(reagents['mq'], dest_all, n=3, note="Wash 3x MQ")
    wash(reagents['pbs'], dest_all, n=1, minutes=3, note="PBS, 3 min")

    # --- 4. AEC development ---------------------------------------------------
    apply(reagents['aec'], dest_all, minutes=20, note="ImmPACT AEC substrate, 20 min RT")
    wash(reagents['mq'], dest_all, n=3, note="Wash 3x MQ")

    # --- 5. Counterstain ------------------------------------------------------
    apply(reagents['hematoxylin'], dest_all, minutes=1, note="Filtered haematoxylin, 1 min")
    wash(reagents['mq'], dest_all, n=6, note="Wash 6x MQ")

    # --- 6. Hand over to the arm ----------------------------------------------
    wash(reagents['mq'], dest_all, n=1, note="MQ water - sections must not dry")
    if IS_LAST_CYCLE:
        protocol.comment("FINAL CYCLE COMPLETE - image, then coverslip manually "
                         "with VectaMount AQ.")
    else:
        protocol.comment(f"CYCLE {CYCLE_INDEX} COMPLETE - sections under MQ water, "
                         "ready for imaging. Do not let them dry, do not coverslip.")

    # ==========================================================================
    # Usage report
    # ==========================================================================
    protocol.comment("")
    protocol.comment("===== REAGENT USAGE THIS CYCLE =====")
    for key, r in reagents.items():
        protocol.comment(f"  {key:<14} used {r.used / 1000:7.2f} ml   "
                         f"(remaining {max(r.volume, 0) / 1000:.2f} ml)")
